### ISSUE TITLE
Not working on Magisk V27

### ISSUE THREAD

**Issue by TheJNXx** [Magisk-Modules-Alt-Repo/NavBar_Resize_AOSP#1]

**Comment by GlitchedCod** [comment]
Same issue here.
Android 14 had thèse folders :
/system/product/overlay/OldNavBar/NavbarOldOverlay.apk
/system/product/overlay/NavigationBarMode3Button/NavigationBarMode3ButtonOverlay.apk
Maybe a New path could help.

**Comment by Atrate** [comment]
@Jennifer2005x @GlitchedCod Do you know if this module works on earlier Android versions, like A13/A12 or lower?

**Comment by TheJNXx** [comment]
I just know it works on Android 10, but it only works on Magisk 25

**Comment by CrazyBytesVE** [comment]
Support for Android 14 and Magisk 27 added.

Tested with Matrixx ROM 10.5.3, Android 14 QPR2, Xiaomi Poco F5.
